server:
  port: 8081

spring:
  application:
    name: gateway-service
  cloud:
   gateway:
    discovery:
     locator:
       enabled: true

eureka:
 client:
   service-url:
    defaultZone: http://localhost:8080/eureka/



